language: cpp

os:
  - osx

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install gcc glfw3 sdl2 glm qt5 && brew link --force qt5 && brew upgrade boost && brew cleanup boost; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then export CXXFLAGS="-std=c++11 -stdlib=libc++"; fi

script:
  - qmake -project
  - qmake Kuplung.pro -r -spec macx-clang CONFIG+=x86_64
  - make