language: cpp
os: osx
compiler:
  - clang
  - gcc

before_install:
  - brew update
  - brew install sdl2 glm minizip glfw3 assimp protobuf lua@5.3

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../Kuplung && cmake --build ./
