language: cpp

os:
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install glfw3 sdl2 glm boost; fi

script:
  - qmake -project
  - qmake Kuplung.pro
  - make