language: cpp
os: osx
compiler: g++

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then
    brew update
    && brew install glfw3 sdl2 glm
    && brew upgrade boost && brew cleanup boost; fi

install:
  - export CXX="g++-4.8"

script:
  - qmake -project
  - qmake Kuplung.pro
  - export CXX="-std=c++11 -stdlib=libc++"
  - make clean
  - make
