language: cpp

os:
  - osx

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install glfw3 sdl2 glm qt5 && brew upgrade boost && brew cleanup boost; fi

script:
  - qmake -project
  - qmake Kuplung.pro
  - make