language: cpp

os:
  - osx

compiler:
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then
    brew update
    && brew glm; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
    export CXXFLAGS="-std=c++11 -stdlib=libc++"
    export LFLAGS="-stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64"
    ; fi

install:

before_script:

script:
  - qmake -project
  - qmake Kuplung.pro -r -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
  - if [ $TRAVIS_OS_NAME == osx ]; then
      QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - export CXX="-std=c++11 -stdlib=libc++"
  - make clean
  - make
