# language: cpp

# os:
#   - osx

# compiler:
#   - clang

# before_install:
#   - if [ $TRAVIS_OS_NAME == osx ]; then
#     brew update
#     && brew install glfw3 sdl2 glm qt5
#     && brew link --force qt5
#     && brew upgrade boost && brew cleanup boost; fi
#   - if [ $TRAVIS_OS_NAME == osx ]; then
#     export CXXFLAGS="-std=c++11 -stdlib=libc++"; fi

# before_script:
#   - qmake -project
#   - qmake Kuplung.pro

# script:
#   - make clean
#   - make
