language: cpp

os: osx

before_install:
  - brew update
#  - brew install cmake

script:
  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build ./Kuplung && cmake --build ./Kuplung --target coveralls
