language: cpp

os:
  - osx

compiler:
  - clang

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then
    brew update
    && brew install glm; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
    export CXXFLAGS="-std=c++11 -stdlib=libc++"
    export LFLAGS="-stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64"
    ; fi

script:
  - qmake -project
  - qmake Kuplung.pro -r -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
  - if [ $TRAVIS_OS_NAME == osx ]; then
      QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - export CXX="-std=c++11 -stdlib=libc++"
  - make clean
  - make
