environment:
  P: "c:/projects/"

branches:
  only:
    - master

os: Visual Studio 2017

platform: x64
configuration: Release

build:
  project: INSTALL.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\Kuplung
  - cmake -G "Visual Studio 15 2017 Win64"
